train_data: norway/norway-1600-train.npz
test_data: norway/norway-1600-test.npz
epochs: 500
device: cuda:7
batch_size: 128
dataset_name: norway-1600
config: configs/hyperparameter-config-Transformer-LPE.yaml
siamese: 1
vn: 0