finetune_from: /data/sam/terrain/models/single_dataset/norway/norway-250-50k-train/MLP/no-vn/siamese/p-1/mse_loss/<modelname>/debug
train_data: norway/norway-250-50k-train
epochs: 1000
device: cuda:2
batch_size: 256
dataset_name: norway/norway-2k-50k-train
config: configs/w-64-hw-128-dropout.yml
siamese: 1
vn: 0
max: 1
loss: mse_loss
aggr: 'sum+diff'
layer_type: 'MLP'
p: 1
include_edge_attr: 1
finetune: 1
uncertainty_model: 0
lr: 0.001