train_data: norway/norway-250-50k-train
test_data: dummy-test.npz
epochs: 500
device: cuda:4
batch_size: 256
dataset_name: norway/norway-250-50k-train
config: configs/w-64-hw-128-dropout.yml
siamese: 1
vn: 0
max: 1
loss: mse_loss
aggr: 'sum+diff'
layer_type: 'MLP'
p: 1
include_edge_attr: 1
finetune: 0
lr: 0.0001
finetune_from: 'none'