train_data: norway/norway-small-full.npz
test_data: norway/norway-small-full-test.npz
epochs: 500
device: cuda:0
batch_size: 32
dataset_name: norway-small
config: configs/best-config-GNN.yml
siamese: 0
vn: 0
max: 1
loss: mse_loss
aggr: 'max'
layer_type: 'GATConv'