GCN-0:
  final:
    hidden: 16
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 2
    output: 16
GCN-1:
  final:
    hidden: 64
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 8
  phi:
    hidden: 16
    input: 8
    layers: 4
    output: 16
GCN-10:
  final:
    hidden: 256
    input: 8
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 6
    output: 8
GCN-11:
  final:
    hidden: 256
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 2
    output: 16
GCN-12:
  final:
    hidden: 128
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 2
    output: 8
GCN-13:
  final:
    hidden: 128
    input: 16
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 4
    output: 16
GCN-14:
  final:
    hidden: 16
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 4
    output: 128
GCN-15:
  final:
    hidden: 64
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 6
    output: 128
GCN-16:
  final:
    hidden: 32
    input: 64
    layers: 6
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 6
    output: 64
GCN-17:
  final:
    hidden: 256
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 4
    output: 64
GCN-18:
  final:
    hidden: 32
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 4
    output: 64
GCN-19:
  final:
    hidden: 16
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 2
    output: 8
GCN-2:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 8
  phi:
    hidden: 32
    input: 8
    layers: 6
    output: 128
GCN-20:
  final:
    hidden: 32
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 4
    output: 16
GCN-21:
  final:
    hidden: 256
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 4
    output: 64
GCN-22:
  final:
    hidden: 128
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 4
    output: 8
GCN-23:
  final:
    hidden: 64
    input: 64
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 2
    output: 64
GCN-24:
  final:
    hidden: 16
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 2
    output: 128
GCN-25:
  final:
    hidden: 16
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 16
  phi:
    hidden: 16
    input: 16
    layers: 2
    output: 32
GCN-26:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 4
    output: 128
GCN-27:
  final:
    hidden: 16
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 2
    output: 32
GCN-28:
  final:
    hidden: 32
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 6
    output: 32
GCN-29:
  final:
    hidden: 16
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 4
    output: 64
GCN-3:
  final:
    hidden: 64
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 6
    output: 8
GCN-30:
  final:
    hidden: 64
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 6
    output: 16
GCN-31:
  final:
    hidden: 128
    input: 16
    layers: 6
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 32
  phi:
    hidden: 256
    input: 32
    layers: 4
    output: 16
GCN-32:
  final:
    hidden: 16
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 6
    output: 8
GCN-33:
  final:
    hidden: 128
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 6
    output: 32
GCN-34:
  final:
    hidden: 128
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 32
  phi:
    hidden: 128
    input: 32
    layers: 2
    output: 32
GCN-35:
  final:
    hidden: 16
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 2
    output: 16
GCN-36:
  final:
    hidden: 16
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 4
    output: 128
GCN-37:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 4
    output: 128
GCN-38:
  final:
    hidden: 16
    input: 16
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 4
    output: 16
GCN-39:
  final:
    hidden: 128
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 4
    output: 16
GCN-4:
  final:
    hidden: 64
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 4
    output: 8
GCN-40:
  final:
    hidden: 32
    input: 16
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 6
    output: 16
GCN-41:
  final:
    hidden: 32
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 2
    output: 128
GCN-42:
  final:
    hidden: 256
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 6
    output: 128
GCN-43:
  final:
    hidden: 64
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 2
    output: 32
GCN-44:
  final:
    hidden: 16
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 6
    output: 8
GCN-45:
  final:
    hidden: 128
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 6
    output: 16
GCN-46:
  final:
    hidden: 256
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 2
    output: 32
GCN-47:
  final:
    hidden: 16
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 6
    output: 32
GCN-48:
  final:
    hidden: 16
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 6
    output: 128
GCN-49:
  final:
    hidden: 128
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 4
    output: 32
GCN-5:
  final:
    hidden: 16
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 6
    output: 16
GCN-50:
  final:
    hidden: 256
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 6
    output: 128
GCN-51:
  final:
    hidden: 64
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 2
    output: 32
GCN-52:
  final:
    hidden: 64
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 4
    output: 64
GCN-53:
  final:
    hidden: 64
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 6
    output: 128
GCN-54:
  final:
    hidden: 32
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 2
    output: 8
GCN-55:
  final:
    hidden: 128
    input: 64
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 6
    output: 64
GCN-56:
  final:
    hidden: 16
    input: 64
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 4
    output: 64
GCN-57:
  final:
    hidden: 16
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 4
    output: 16
GCN-58:
  final:
    hidden: 32
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 2
    output: 128
GCN-59:
  final:
    hidden: 32
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 6
    output: 128
GCN-6:
  final:
    hidden: 256
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 8
  phi:
    hidden: 32
    input: 8
    layers: 2
    output: 32
GCN-60:
  final:
    hidden: 256
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 4
    output: 32
GCN-61:
  final:
    hidden: 128
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 2
    output: 8
GCN-62:
  final:
    hidden: 32
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 6
    output: 64
GCN-63:
  final:
    hidden: 256
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 6
    output: 128
GCN-64:
  final:
    hidden: 16
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 4
    output: 32
GCN-65:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 6
    output: 128
GCN-66:
  final:
    hidden: 256
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 128
  phi:
    hidden: 256
    input: 128
    layers: 4
    output: 32
GCN-67:
  final:
    hidden: 64
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 6
    output: 128
GCN-68:
  final:
    hidden: 256
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 4
    output: 16
GCN-69:
  final:
    hidden: 256
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 6
    output: 16
GCN-7:
  final:
    hidden: 16
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 2
    output: 32
GCN-70:
  final:
    hidden: 64
    input: 128
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 16
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 6
    output: 128
GCN-71:
  final:
    hidden: 64
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 32
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 6
    output: 32
GCN-72:
  final:
    hidden: 64
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 64
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 2
    output: 32
GCN-73:
  final:
    hidden: 16
    input: 32
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 2
    output: 32
GCN-74:
  final:
    hidden: 32
    input: 8
    layers: 6
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 128
  phi:
    hidden: 256
    input: 128
    layers: 2
    output: 8
GCN-8:
  final:
    hidden: 32
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 128
    output: 8
  phi:
    hidden: 16
    input: 8
    layers: 2
    output: 128
GCN-9:
  final:
    hidden: 16
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GCNConv
    layers: 256
    output: 8
  phi:
    hidden: 16
    input: 8
    layers: 6
    output: 32
