GAT-0:
  final:
    hidden: 256
    input: 128
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 16
    output: 8
  phi:
    hidden: 16
    input: 8
    layers: 2
    output: 128
GAT-1:
  final:
    hidden: 16
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 32
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 1
    output: 8
GAT-10:
  final:
    hidden: 128
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 16
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 1
    output: 16
GAT-11:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 32
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 1
    output: 128
GAT-12:
  final:
    hidden: 16
    input: 8
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 64
    output: 8
  phi:
    hidden: 16
    input: 8
    layers: 2
    output: 8
GAT-13:
  final:
    hidden: 16
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 128
    output: 8
  phi:
    hidden: 32
    input: 8
    layers: 3
    output: 8
GAT-14:
  final:
    hidden: 128
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 256
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 1
    output: 16
GAT-15:
  final:
    hidden: 16
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 16
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 1
    output: 64
GAT-16:
  final:
    hidden: 256
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 32
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 2
    output: 16
GAT-17:
  final:
    hidden: 64
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 64
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 2
    output: 32
GAT-18:
  final:
    hidden: 64
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 128
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 3
    output: 8
GAT-19:
  final:
    hidden: 256
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 256
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 1
    output: 16
GAT-2:
  final:
    hidden: 256
    input: 16
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 64
    output: 8
  phi:
    hidden: 32
    input: 8
    layers: 2
    output: 16
GAT-20:
  final:
    hidden: 256
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 16
    output: 16
  phi:
    hidden: 16
    input: 16
    layers: 3
    output: 8
GAT-21:
  final:
    hidden: 128
    input: 64
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 32
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 2
    output: 64
GAT-22:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 64
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 2
    output: 128
GAT-23:
  final:
    hidden: 32
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 128
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 2
    output: 32
GAT-24:
  final:
    hidden: 32
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 256
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 1
    output: 32
GAT-25:
  final:
    hidden: 32
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 16
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 3
    output: 64
GAT-26:
  final:
    hidden: 32
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 32
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 3
    output: 16
GAT-27:
  final:
    hidden: 64
    input: 16
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 64
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 3
    output: 16
GAT-28:
  final:
    hidden: 128
    input: 8
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 128
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 3
    output: 8
GAT-29:
  final:
    hidden: 32
    input: 8
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 256
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 2
    output: 8
GAT-3:
  final:
    hidden: 16
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 128
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 2
    output: 64
GAT-30:
  final:
    hidden: 16
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 16
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 16
GAT-31:
  final:
    hidden: 64
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 32
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 1
    output: 64
GAT-32:
  final:
    hidden: 128
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 64
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 1
    output: 8
GAT-33:
  final:
    hidden: 128
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 128
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 1
    output: 64
GAT-34:
  final:
    hidden: 64
    input: 64
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 256
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 64
GAT-35:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 16
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 2
    output: 128
GAT-36:
  final:
    hidden: 64
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 32
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 3
    output: 16
GAT-37:
  final:
    hidden: 16
    input: 16
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 64
    output: 32
  phi:
    hidden: 128
    input: 32
    layers: 3
    output: 16
GAT-38:
  final:
    hidden: 32
    input: 16
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 128
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 2
    output: 16
GAT-39:
  final:
    hidden: 32
    input: 8
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 256
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 3
    output: 8
GAT-4:
  final:
    hidden: 128
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 256
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 1
    output: 8
GAT-40:
  final:
    hidden: 64
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 16
    output: 32
  phi:
    hidden: 128
    input: 32
    layers: 2
    output: 64
GAT-41:
  final:
    hidden: 128
    input: 64
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 32
    output: 32
  phi:
    hidden: 256
    input: 32
    layers: 2
    output: 64
GAT-42:
  final:
    hidden: 32
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 64
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 64
GAT-43:
  final:
    hidden: 128
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 128
    output: 32
  phi:
    hidden: 256
    input: 32
    layers: 2
    output: 16
GAT-44:
  final:
    hidden: 256
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 256
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 3
    output: 8
GAT-45:
  final:
    hidden: 32
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 16
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 1
    output: 32
GAT-46:
  final:
    hidden: 16
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 32
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 3
    output: 8
GAT-47:
  final:
    hidden: 16
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 64
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 3
    output: 8
GAT-48:
  final:
    hidden: 64
    input: 64
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 128
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 2
    output: 64
GAT-49:
  final:
    hidden: 32
    input: 128
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 256
    output: 64
  phi:
    hidden: 16
    input: 64
    layers: 2
    output: 128
GAT-5:
  final:
    hidden: 256
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 16
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 3
    output: 8
GAT-50:
  final:
    hidden: 128
    input: 128
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 16
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 2
    output: 128
GAT-51:
  final:
    hidden: 128
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 32
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 2
    output: 16
GAT-52:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 64
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 1
    output: 128
GAT-53:
  final:
    hidden: 64
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 128
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 3
    output: 64
GAT-54:
  final:
    hidden: 32
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 256
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 2
    output: 8
GAT-55:
  final:
    hidden: 64
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 16
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 1
    output: 8
GAT-56:
  final:
    hidden: 64
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 32
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 3
    output: 8
GAT-57:
  final:
    hidden: 256
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 64
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 1
    output: 8
GAT-58:
  final:
    hidden: 32
    input: 128
    layers: 3
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 128
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 2
    output: 128
GAT-59:
  final:
    hidden: 128
    input: 64
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 256
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 1
    output: 64
GAT-6:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 32
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 3
    output: 128
GAT-60:
  final:
    hidden: 256
    input: 8
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 16
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 2
    output: 8
GAT-61:
  final:
    hidden: 128
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 32
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 3
    output: 8
GAT-62:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 64
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 1
    output: 128
GAT-63:
  final:
    hidden: 32
    input: 32
    layers: 1
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 128
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 1
    output: 32
GAT-64:
  final:
    hidden: 64
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 2
    input: 3
    layer_type: GATConv
    layers: 256
    output: 128
  phi:
    hidden: 256
    input: 128
    layers: 2
    output: 32
GAT-65:
  final:
    hidden: 64
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 16
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 2
    output: 8
GAT-66:
  final:
    hidden: 128
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 32
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 2
    output: 8
GAT-67:
  final:
    hidden: 128
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 64
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 1
    output: 8
GAT-68:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 128
    output: 128
  phi:
    hidden: 256
    input: 128
    layers: 1
    output: 128
GAT-69:
  final:
    hidden: 32
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 256
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 3
    output: 16
GAT-7:
  final:
    hidden: 64
    input: 128
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 64
    output: 8
  phi:
    hidden: 64
    input: 8
    layers: 3
    output: 128
GAT-70:
  final:
    hidden: 64
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 16
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 1
    output: 16
GAT-71:
  final:
    hidden: 64
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 32
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 2
    output: 128
GAT-72:
  final:
    hidden: 16
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 64
    output: 128
  phi:
    hidden: 256
    input: 128
    layers: 3
    output: 128
GAT-73:
  final:
    hidden: 32
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 128
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 1
    output: 64
GAT-74:
  final:
    hidden: 16
    input: 16
    layers: 1
    output: 1
  gnn:
    hidden: 4
    input: 3
    layer_type: GATConv
    layers: 256
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 1
    output: 16
GAT-8:
  final:
    hidden: 256
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 128
    output: 8
  phi:
    hidden: 256
    input: 8
    layers: 3
    output: 64
GAT-9:
  final:
    hidden: 256
    input: 32
    layers: 1
    output: 1
  gnn:
    hidden: 3
    input: 3
    layer_type: GATConv
    layers: 256
    output: 8
  phi:
    hidden: 128
    input: 8
    layers: 2
    output: 32
