Transfomer-0:
  final:
    hidden: 256
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer
    layers: 2
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 4
    output: 128
Transfomer-1:
  final:
    hidden: 64
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer
    layers: 2
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 3
    output: 8
Transfomer-10:
  final:
    hidden: 32
    input: 128
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer
    layers: 2
    output: 64
  phi:
    hidden: 128
    input: 64
    layers: 3
    output: 128
Transfomer-11:
  final:
    hidden: 128
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer
    layers: 2
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 4
    output: 64
Transfomer-12:
  final:
    hidden: 256
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer
    layers: 2
    output: 128
  phi:
    hidden: 16
    input: 128
    layers: 4
    output: 8
Transfomer-13:
  final:
    hidden: 64
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer
    layers: 2
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 2
    output: 64
Transfomer-14:
  final:
    hidden: 16
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer
    layers: 2
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 4
    output: 16
Transfomer-15:
  final:
    hidden: 128
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer
    layers: 2
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 3
    output: 64
Transfomer-2:
  final:
    hidden: 256
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer
    layers: 2
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 3
    output: 64
Transfomer-3:
  final:
    hidden: 32
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer
    layers: 2
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 3
    output: 128
Transfomer-4:
  final:
    hidden: 256
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer
    layers: 2
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 2
    output: 64
Transfomer-5:
  final:
    hidden: 256
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer
    layers: 2
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 4
    output: 64
Transfomer-6:
  final:
    hidden: 128
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer
    layers: 2
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 4
    output: 64
Transfomer-7:
  final:
    hidden: 256
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer
    layers: 2
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 3
    output: 32
Transfomer-8:
  final:
    hidden: 16
    input: 16
    layers: 4
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer
    layers: 2
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 4
    output: 16
Transfomer-9:
  final:
    hidden: 16
    input: 128
    layers: 3
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer
    layers: 2
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 3
    output: 128
