Transformer-LPE-0:
  final:
    hidden: 64
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 4
    output: 64
Transformer-LPE-1:
  final:
    hidden: 16
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 16
  phi:
    hidden: 128
    input: 16
    layers: 2
    output: 64
Transformer-LPE-10:
  final:
    hidden: 16
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 2
    output: 8
Transformer-LPE-11:
  final:
    hidden: 128
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 2
    output: 64
Transformer-LPE-12:
  final:
    hidden: 32
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 128
  phi:
    hidden: 32
    input: 128
    layers: 3
    output: 64
Transformer-LPE-13:
  final:
    hidden: 256
    input: 8
    layers: 4
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 2
    output: 8
Transformer-LPE-14:
  final:
    hidden: 256
    input: 64
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 4
    output: 64
Transformer-LPE-15:
  final:
    hidden: 32
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 4
    output: 32
Transformer-LPE-2:
  final:
    hidden: 32
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 3
    output: 32
Transformer-LPE-3:
  final:
    hidden: 16
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 16
  phi:
    hidden: 256
    input: 16
    layers: 4
    output: 8
Transformer-LPE-4:
  final:
    hidden: 32
    input: 16
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 2
    output: 16
Transformer-LPE-5:
  final:
    hidden: 32
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 8
Transformer-LPE-6:
  final:
    hidden: 64
    input: 128
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 128
Transformer-LPE-7:
  final:
    hidden: 16
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 32
  phi:
    hidden: 16
    input: 32
    layers: 2
    output: 16
Transformer-LPE-8:
  final:
    hidden: 256
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 64
  phi:
    hidden: 256
    input: 64
    layers: 4
    output: 64
Transformer-LPE-9:
  final:
    hidden: 64
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: Transformer-LPE
    layers: 2
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 2
    output: 64
