GCN2Conv-0:
  final:
    hidden: 64
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 16
  phi:
    hidden: 16
    input: 16
    layers: 3
    output: 64
GCN2Conv-1:
  final:
    hidden: 256
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 16
  phi:
    hidden: 64
    input: 16
    layers: 4
    output: 128
GCN2Conv-10:
  final:
    hidden: 128
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 64
  phi:
    hidden: 64
    input: 64
    layers: 4
    output: 32
GCN2Conv-11:
  final:
    hidden: 32
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 64
  phi:
    hidden: 16
    input: 64
    layers: 4
    output: 8
GCN2Conv-12:
  final:
    hidden: 32
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 3
    output: 64
GCN2Conv-13:
  final:
    hidden: 256
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 3
    output: 64
GCN2Conv-14:
  final:
    hidden: 16
    input: 64
    layers: 4
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 128
  phi:
    hidden: 128
    input: 128
    layers: 3
    output: 64
GCN2Conv-15:
  final:
    hidden: 16
    input: 128
    layers: 4
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 128
  phi:
    hidden: 64
    input: 128
    layers: 4
    output: 128
GCN2Conv-2:
  final:
    hidden: 32
    input: 16
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 16
  phi:
    hidden: 16
    input: 16
    layers: 3
    output: 16
GCN2Conv-3:
  final:
    hidden: 16
    input: 8
    layers: 2
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 16
  phi:
    hidden: 32
    input: 16
    layers: 3
    output: 8
GCN2Conv-4:
  final:
    hidden: 128
    input: 32
    layers: 4
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 32
  phi:
    hidden: 64
    input: 32
    layers: 2
    output: 32
GCN2Conv-5:
  final:
    hidden: 128
    input: 128
    layers: 2
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 32
  phi:
    hidden: 128
    input: 32
    layers: 2
    output: 128
GCN2Conv-6:
  final:
    hidden: 32
    input: 8
    layers: 3
    output: 1
  gnn:
    hidden: 128
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 32
  phi:
    hidden: 32
    input: 32
    layers: 3
    output: 8
GCN2Conv-7:
  final:
    hidden: 16
    input: 32
    layers: 2
    output: 1
  gnn:
    hidden: 256
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 32
  phi:
    hidden: 128
    input: 32
    layers: 2
    output: 32
GCN2Conv-8:
  final:
    hidden: 256
    input: 64
    layers: 2
    output: 1
  gnn:
    hidden: 32
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 64
  phi:
    hidden: 16
    input: 64
    layers: 3
    output: 64
GCN2Conv-9:
  final:
    hidden: 256
    input: 32
    layers: 3
    output: 1
  gnn:
    hidden: 64
    input: 3
    layer_type: GCN2Conv
    layers: 2
    output: 64
  phi:
    hidden: 32
    input: 64
    layers: 2
    output: 32
