train_data: norway/norway-1600-train.npz
test_data: norway/norway-1600-test.npz
epochs: 500
device: cuda:2
batch_size: 128
dataset_name: norway-1600
config: configs/hyperparameter-config-GCN2.yaml
siamese: 0
vn: 0